#!/usr/bin/env bash
# Usage: project-cluster bootstrap <ip> [<discovery_url> <bootstrap-count>]
# Summary: Initialize the server at <ip>. Adds the machine to this cluster's pool of resources.

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo "Bootstrapping $1 ..."

host=core@$1
discovery_url=$2
bootstrap_count=$3

cloud_config_tmp_dir=/tmp/project-cluster
mkdir -p $cloud_config_tmp_dir
cloud_config_tmp=$cloud_config_tmp_dir/cloudinit.conf

cat <<EOF > $cloud_config_tmp
#cloud-config
coreos:
  etcd:
    name: node\$public_ipv4
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: $discovery_url
    addr: \$private_ipv4:4001
    peer-addr: \$private_ipv4:7001
    advertise-client-urls: http://\$public_ipv4:2379
    initial-advertise-peer-urls: http://\$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://\$private_ipv4:2380,http://\$private_ipv4:7001
  fleet:
      public-ip: \$public_ipv4
      metadata: region=us-east
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: consul.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=Consul service directory

        [Service]
        ExecStartPre=-/usr/bin/mkdir /opt
        ExecStartPre=-/usr/bin/wget --retry-connrefused -t 0 -nc -O /opt/bootstrap-consul https://gist.githubusercontent.com/will-ob/658b1d573a057c0d723a/raw/26dc34561f30b166547e77fcfe4fdbca6dd71885/bootstrap-consul.sh
        ExecStartPre=-/usr/bin/chmod +x /opt/bootstrap-consul
        ExecStart=/opt/bootstrap-consul $bootstrap_count

EOF

# Copy & run cloudconfig on machine
scp -i ~/.project-cluster/ident.pem $cloud_config_tmp $host:/home/core/cloudinit.conf
ssh -i ~/.project-cluster/ident.pem $host "sudo coreos-cloudinit --from-file /home/core/cloudinit.conf"

